<?php

use App\{Attendance,Employee};
use Illuminate\Database\Seeder;

class AttendanceSeeder extends Seeder
{
    public function run()
    {
        $datas = [
            // employee 1 
            [
                'date' => "2021-04-01",
                'time_in' => "08:00:00",
                'time_out' => "17:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::first()->id,
            ],
            [
                'date' => "2021-04-02",
                'time_in' => "08:00:00",
                'time_out' => "17:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::first()->id,
            ],
            [
                'date' => "2021-04-03",
                'time_in' => "08:00:00",
                'time_out' => "17:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::first()->id,
            ],
            [
                'date' => "2021-04-04",
                'time_in' => "08:00:00",
                'time_out' => "17:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::first()->id,
            ],
            [
                'date' => "2021-04-05",
                'time_in' => "08:00:00",
                'time_out' => "17:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::first()->id,
            ],
            [
                'date' => "2021-04-06",
                'time_in' => "08:00:00",
                'time_out' => "17:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::first()->id,
            ],
            [
                'date' => "2021-04-07",
                'time_in' => "08:00:00",
                'time_out' => "17:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::first()->id,
            ],
            [
                'date' => "2021-04-08",
                'time_in' => "08:00:00",
                'time_out' => "17:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::first()->id,
            ],
            [
                'date' => "2021-04-09",
                'time_in' => "08:00:00",
                'time_out' => "17:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::first()->id,
            ],
            [
                'date' => "2021-04-10",
                'time_in' => "08:00:00",
                'time_out' => "17:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::first()->id,
            ],
            [
                'date' => "2021-04-11",
                'time_in' => "08:00:00",
                'time_out' => "17:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::first()->id,
            ],
            [
                'date' => "2021-04-12",
                'time_in' => "08:00:00",
                'time_out' => "17:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::first()->id,
            ],
            [
                'date' => "2021-04-13",
                'time_in' => "08:00:00",
                'time_out' => "17:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::first()->id,
            ],
            [
                'date' => "2021-04-14",
                'time_in' => "08:00:00",
                'time_out' => "17:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::first()->id,
            ],
            [
                'date' => "2021-04-15",
                'time_in' => "08:00:00",
                'time_out' => "17:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::first()->id,
            ],
            [
                'date' => "2021-04-16",
                'time_in' => "08:00:00",
                'time_out' => "17:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::first()->id,
            ],
            [
                'date' => "2021-04-17",
                'time_in' => "08:00:00",
                'time_out' => "17:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::first()->id,
            ],
            [
                'date' => "2021-04-18",
                'time_in' => "08:00:00",
                'time_out' => "17:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::first()->id,
            ],
            [
                'date' => "2021-04-19",
                'time_in' => "08:00:00",
                'time_out' => "17:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::first()->id,
            ],
            [
                'date' => "2021-04-20",
                'time_in' => "08:00:00",
                'time_out' => "17:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::first()->id,
            ],
            // end employee 1

            // employee 2
            [
                'date' => "2021-04-01",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",2)->first()->id,
            ],
            [
                'date' => "2021-04-02",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",2)->first()->id,
            ],
            [
                'date' => "2021-04-03",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",2)->first()->id,
            ],
            [
                'date' => "2021-04-04",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",2)->first()->id,
            ],
            [
                'date' => "2021-04-05",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",2)->first()->id,
            ],
            [
                'date' => "2021-04-06",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",2)->first()->id,
            ],
            [
                'date' => "2021-04-07",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",2)->first()->id,
            ],
            [
                'date' => "2021-04-08",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",2)->first()->id,
            ],
            [
                'date' => "2021-04-09",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",2)->first()->id,
            ],
            [
                'date' => "2021-04-10",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",2)->first()->id,
            ],
            [
                'date' => "2021-04-11",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",2)->first()->id,
            ],
            [
                'date' => "2021-04-12",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",2)->first()->id,
            ],
            [
                'date' => "2021-04-13",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",2)->first()->id,
            ],
            [
                'date' => "2021-04-14",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",2)->first()->id,
            ],
            [
                'date' => "2021-04-15",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",2)->first()->id,
            ],
            [
                'date' => "2021-04-16",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",2)->first()->id,
            ],
            [
                'date' => "2021-04-17",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",2)->first()->id,
            ],
            [
                'date' => "2021-04-18",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",2)->first()->id,
            ],
            [
                'date' => "2021-04-19",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",2)->first()->id,
            ],
            [
                'date' => "2021-04-20",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",2)->first()->id,
            ],
            //end of employee 2
            // employee 3
            [
                'date' => "2021-04-01",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",3)->first()->id,
            ],
            [
                'date' => "2021-04-02",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",3)->first()->id,
            ],
            [
                'date' => "2021-04-03",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",3)->first()->id,
            ],
            [
                'date' => "2021-04-04",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",3)->first()->id,
            ],
            [
                'date' => "2021-04-05",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",3)->first()->id,
            ],
            [
                'date' => "2021-04-06",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",3)->first()->id,
            ],
            [
                'date' => "2021-04-07",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",3)->first()->id,
            ],
            [
                'date' => "2021-04-08",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",3)->first()->id,
            ],
            [
                'date' => "2021-04-09",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",3)->first()->id,
            ],
            [
                'date' => "2021-04-10",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",3)->first()->id,
            ],
            [
                'date' => "2021-04-11",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",3)->first()->id,
            ],
            [
                'date' => "2021-04-12",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",3)->first()->id,
            ],
            [
                'date' => "2021-04-13",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",3)->first()->id,
            ],
            [
                'date' => "2021-04-14",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",3)->first()->id,
            ],
            [
                'date' => "2021-04-15",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",3)->first()->id,
            ],
            [
                'date' => "2021-04-16",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",3)->first()->id,
            ],
            [
                'date' => "2021-04-17",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",3)->first()->id,
            ],
            [
                'date' => "2021-04-18",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",3)->first()->id,
            ],
            [
                'date' => "2021-04-19",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",3)->first()->id,
            ],
            [
                'date' => "2021-04-20",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",3)->first()->id,
            ],
            //end of employee 3

            // employee 4
            [
                'date' => "2021-04-01",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",4)->first()->id,
            ],
            [
                'date' => "2021-04-02",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",4)->first()->id,
            ],
            [
                'date' => "2021-04-03",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",4)->first()->id,
            ],
            [
                'date' => "2021-04-04",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",4)->first()->id,
            ],
            [
                'date' => "2021-04-05",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",4)->first()->id,
            ],
            [
                'date' => "2021-04-06",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",4)->first()->id,
            ],
            [
                'date' => "2021-04-07",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",4)->first()->id,
            ],
            [
                'date' => "2021-04-08",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",4)->first()->id,
            ],
            [
                'date' => "2021-04-09",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",4)->first()->id,
            ],
            [
                'date' => "2021-04-10",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",4)->first()->id,
            ],
            [
                'date' => "2021-04-11",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",4)->first()->id,
            ],
            [
                'date' => "2021-04-12",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",4)->first()->id,
            ],
            [
                'date' => "2021-04-13",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",4)->first()->id,
            ],
            [
                'date' => "2021-04-14",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",4)->first()->id,
            ],
            [
                'date' => "2021-04-15",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",4)->first()->id,
            ],
            [
                'date' => "2021-04-16",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",4)->first()->id,
            ],
            [
                'date' => "2021-04-17",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",4)->first()->id,
            ],
            [
                'date' => "2021-04-18",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",4)->first()->id,
            ],
            [
                'date' => "2021-04-19",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",4)->first()->id,
            ],
            [
                'date' => "2021-04-20",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",4)->first()->id,
            ],
            //end of employee 4

            // employee 5
            [
                'date' => "2021-04-01",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",5)->first()->id,
            ],
            [
                'date' => "2021-04-02",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",5)->first()->id,
            ],
            [
                'date' => "2021-04-03",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",5)->first()->id,
            ],
            [
                'date' => "2021-04-04",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",5)->first()->id,
            ],
            [
                'date' => "2021-04-05",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",5)->first()->id,
            ],
            [
                'date' => "2021-04-06",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",5)->first()->id,
            ],
            [
                'date' => "2021-04-07",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",5)->first()->id,
            ],
            [
                'date' => "2021-04-08",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",5)->first()->id,
            ],
            [
                'date' => "2021-04-09",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",5)->first()->id,
            ],
            [
                'date' => "2021-04-10",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",5)->first()->id,
            ],
            [
                'date' => "2021-04-11",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",5)->first()->id,
            ],
            [
                'date' => "2021-04-12",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",5)->first()->id,
            ],
            [
                'date' => "2021-04-13",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",5)->first()->id,
            ],
            [
                'date' => "2021-04-14",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",5)->first()->id,
            ],
            [
                'date' => "2021-04-15",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",5)->first()->id,
            ],
            [
                'date' => "2021-04-16",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",5)->first()->id,
            ],
            [
                'date' => "2021-04-17",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",5)->first()->id,
            ],
            [
                'date' => "2021-04-18",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",5)->first()->id,
            ],
            [
                'date' => "2021-04-19",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",5)->first()->id,
            ],
            [
                'date' => "2021-04-20",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",5)->first()->id,
            ],
            //end of employee 5

            // employee 6
            [
                'date' => "2021-04-01",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",6)->first()->id,
            ],
            [
                'date' => "2021-04-02",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",6)->first()->id,
            ],
            [
                'date' => "2021-04-03",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",6)->first()->id,
            ],
            [
                'date' => "2021-04-04",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",6)->first()->id,
            ],
            [
                'date' => "2021-04-05",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",6)->first()->id,
            ],
            [
                'date' => "2021-04-06",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",6)->first()->id,
            ],
            [
                'date' => "2021-04-07",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",6)->first()->id,
            ],
            [
                'date' => "2021-04-08",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",6)->first()->id,
            ],
            [
                'date' => "2021-04-09",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",6)->first()->id,
            ],
            [
                'date' => "2021-04-10",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",6)->first()->id,
            ],
            [
                'date' => "2021-04-11",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",6)->first()->id,
            ],
            [
                'date' => "2021-04-12",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",6)->first()->id,
            ],
            [
                'date' => "2021-04-13",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",6)->first()->id,
            ],
            [
                'date' => "2021-04-14",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",6)->first()->id,
            ],
            [
                'date' => "2021-04-15",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",6)->first()->id,
            ],
            [
                'date' => "2021-04-16",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",6)->first()->id,
            ],
            [
                'date' => "2021-04-17",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",6)->first()->id,
            ],
            [
                'date' => "2021-04-18",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",6)->first()->id,
            ],
            [
                'date' => "2021-04-19",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",6)->first()->id,
            ],
            [
                'date' => "2021-04-20",
                'time_in' => "09:00:00",
                'time_out' => "18:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",6)->first()->id,
            ],
            //end of employee 6

            // employee 7
            [
                'date' => "2021-04-01",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",7)->first()->id,
            ],
            [
                'date' => "2021-04-02",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",7)->first()->id,
            ],
            [
                'date' => "2021-04-03",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",7)->first()->id,
            ],
            [
                'date' => "2021-04-04",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",7)->first()->id,
            ],
            [
                'date' => "2021-04-05",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",7)->first()->id,
            ],
            [
                'date' => "2021-04-06",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",7)->first()->id,
            ],
            [
                'date' => "2021-04-07",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",7)->first()->id,
            ],
            [
                'date' => "2021-04-08",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",7)->first()->id,
            ],
            [
                'date' => "2021-04-09",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",7)->first()->id,
            ],
            [
                'date' => "2021-04-10",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",7)->first()->id,
            ],
            [
                'date' => "2021-04-11",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",7)->first()->id,
            ],
            [
                'date' => "2021-04-12",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",7)->first()->id,
            ],
            [
                'date' => "2021-04-13",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",7)->first()->id,
            ],
            [
                'date' => "2021-04-14",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",7)->first()->id,
            ],
            [
                'date' => "2021-04-15",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",7)->first()->id,
            ],
            [
                'date' => "2021-04-16",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",7)->first()->id,
            ],
            [
                'date' => "2021-04-17",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",7)->first()->id,
            ],
            [
                'date' => "2021-04-18",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",7)->first()->id,
            ],
            [
                'date' => "2021-04-19",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",7)->first()->id,
            ],
            [
                'date' => "2021-04-20",
                'time_in' => "10:00:00",
                'time_out' => "19:00:00",
                'num_hour' => '540',
                'employee_id' => Employee::where("id",7)->first()->id,
            ],
            //end of employee 7

        ];

        $count = 0;
        foreach ($datas as $key => $data) {
            Attendance::create($data);
            $count++;
        }
        $this->command->info('Inserted '.$count.' Attendances.');
    }
}
